# Generated by Django 2.1.3 on 2018-11-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20181121_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='SchoolInfo',
        ),
    ]
